import type { Metadata } from "next";
import "./globals.css";
import ShareState from "@/components/shared/context/share-state";
import InnerLayout from "@/components/layout/inner-layout";

export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ShareState>
          <InnerLayout>{children}</InnerLayout>
        </ShareState>
      </body>
    </html>
  );
}
